services:

  api:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    depends_on:
      mlflow:
        condition: service_started
    ports:
      - "8000:8000"

  mlflow:
    build: .
    command: mlflow server --artifacts-destination ./mlruns --host 0.0.0.0 --port 5000

    environment:
      - MLFLOW_SERVER_ALLOWED_HOSTS=*

    ports:
      - "5000:5000"

  trainer:
    build: .
    depends_on:
      mlflow:
        condition: service_started
    command: python src/farm_detection/models/training.py
#    environment:
#      - MLFLOW_TRACKING_URI=http://mlflow:5000
