data:
  train_path: ./data/Crop_recommendation.csv
  features:
    - N
    - P
    - K
    - temperature
    - ph
    - humidity
    - rainfall
  target: label

model:
  type: XGBoost
  variables:
    objective: "multi:softmax"
    eval_metric: "logloss"
    tree_method: "hist"
    n_estimators: 100
    verbosity: 0
    random_state: 42

artifacts:
  model_name: "farm-detection-gnb-model"
  model_script: "./src/farm_detection/models/model.py"
  label_encoder: "./artifacts/gnb_model_label_encoder.joblib"
  label_encoder_name: "gnb_model_label_encoder.joblib"
