data:
  train_path: ./data/Crop_recommendation.csv
  features:
    - N
    - P
    - K
    - temperature
    - ph
    - humidity
    - rainfall
  target: label

model:
  type: XGBoost
  variables:
    objective: "multi:softmax"
    eval_metric: "logloss"
    tree_method: "hist"
    n_estimators: 100
    verbosity: 0
    random_state: 42

artifacts:
  model_name: "XGBOOST"
  model_script: "./src/models/model.py"
  decode_path: "/DECODE_MAP/decode_map.pkl"
