data:
  train_path: ./data/Crop_recommendation.csv
  features:
    - N
    - P
    - K
    - temperature
    - ph
    - humidity
    - rainfall
  target: label

model:
  type: GaussianNB
  variables:
    priors: null
    var_smoothing: 1.0e-09

artifacts:
  model_name: "farm-detection-gnb-model"
  model_script: "./src/farm_detection/models/model.py"
  label_encoder: "./artifacts/gnb_model_label_encoder.joblib"
  label_encoder_name: "gnb_model_label_encoder.joblib"
