name: ci

on:  
  push:
    branches: [ "dev" ]
    
jobs:
  black:
    name: Run black code formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install black

      - name: Run black
        run: black .

  test:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install .

      - name: Run tests
        run: pytest

  build:
    name: Build containers
    needs: [black, test] # Ensures build only occurs if CI passes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run Docker containers
        run: docker compose up -d --build

      - name: Wait for containers
        run: sleep 15

      - name: Check if API is running
        run: curl -f http://localhost:8000/ || exit 1

      - name: Check if MLflow is running
        run: curl -f http://localhost:5000/ || exit 1

      - name: Show Container Logs on Failure
        if: failure()
        run: |
          docker compose logs

      - name: Tear down
        if: always() # Ensures containers stop even if curl fails
        run: docker compose down



  